root: true
env:
  es2021: true
  node: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
  ecmaVersion: latest
  sourceType: module
plugins:
  - prefer-arrow
  - '@typescript-eslint'
  - import
  - jsx-a11y
  - testing-library
  - jest-dom
  - jest-extended
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:testing-library/react
  - plugin:jsx-a11y/recommended
  - plugin:jest-dom/recommended
  - plugin:storybook/recommended
  - plugin:jest-extended/all
  - next/core-web-vitals
  - prettier
rules:
  prefer-arrow/prefer-arrow-functions:
    - error
    - classPropertiesAllowed: false
      disallowPrototype: true
      singleReturnOnly: false
  import/order:
    - error
    - alphabetize:
        caseInsensitive: true
        order: asc
      groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
        - object
      newlines-between: always
